# Generated by Django 3.0.3 on 2020-02-10 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Fullname',
            new_name='fullname',
        ),
    ]
